enable: false
inputs:
  up: 17
  down: 27
  open_door: 22
  close_door: 23
  slow_mode: 24
outputs:
  floor_sensors:
    - [5, 6, 13]   #1 [up, middle, down]
    - [19, 26, 16] #2
    - [20, 21, 12] #3
  door_senors: [14, 15] # [closed, open]
  cabin_buttons: [18, 25, 8] # [1, 2, 3]
  floor_buttons: [7, 1, 0] # [1, 2, 3]